-- MySQL Script generated by MySQL Workbench
-- 07/11/17 03:05:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema people
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema people
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `people` DEFAULT CHARACTER SET utf8 ;
USE `people` ;

-- -----------------------------------------------------
-- Table `people`.`people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `people`.`people` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fio` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
